name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to v3
        with:
          node-version: "16" # Updated to Node.js 16

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
